import type {Metadata} from "next";
import "./globals.css";
import {Inter} from 'next/font/google'
import Head from "next/head";
import React from "react";

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <Head>
          <link rel="icon" href="/favicon.ico"/>
      </Head>
      <body className={inter.className}>{children}</body>
      </html>
  );
}
